---
deployment:
  tasks:
    - export DEPLOYPATH=/home/luyandde/public_html/

    # Ensure the target directory exists
    - /bin/mkdir -p $DEPLOYPATH

    # Copy .htaccess file to the deployment path
    - /bin/cp .htaccess $DEPLOYPATH

    # Copy HTML files to the deployment path
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp clarens.html $DEPLOYPATH
    - /bin/cp events.html $DEPLOYPATH
    - /bin/cp faq.html $DEPLOYPATH
    - /bin/cp our-story.html $DEPLOYPATH
    - /bin/cp registry.html $DEPLOYPATH
    - /bin/cp rsvp.html $DEPLOYPATH
    - /bin/cp travel-stay.html $DEPLOYPATH

    # Copy entire directories to the deployment path
    - /bin/cp -r 20240608083421114 $DEPLOYPATH
    - /bin/cp -r 20240608083427370 $DEPLOYPATH
    - /bin/cp -r 20240608083434597 $DEPLOYPATH
    - /bin/cp -r 20240608083439309 $DEPLOYPATH
    - /bin/cp -r 20240608083452756 $DEPLOYPATH
    - /bin/cp -r 20240608083503902 $DEPLOYPATH
    - /bin/cp -r 20240608083509341 $DEPLOYPATH
    - /bin/cp -r 20240608083514638 $DEPLOYPATH
